### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by jhult** [canhlinh/gphoto#1]
Add a [license](https://choosealicense.com/) of sorts.

It would be nice to perhaps combine work with this project: https://github.com/simonedegiacomi/gphotosuploader

**Comment by canhlinh** [comment]
@jhult I've added MIT license to this project.

My goal is build a small lib to help me upload files and testing easier.
This project a small piece of an other project to help people who also want to build their tool.
[He](https://github.com/simonedegiacomi/gphotosuploader) and I are might not in the same page.

Thanks.

**Comment by jhult** [comment]
Thanks!
