### ISSUE TITLE
Joining the efforts

### ISSUE THREAD

**Issue by suntong** [canhlinh/gphoto#2]
Hi @canhlinh, 

Don't know if you are aware of the existing Go lib that uploads to Google Photos -- the

**Unofficial Google Photos uploader and Go library**
https://github.com/simonedegiacomi/gphotosuploader

Maybe you'd like to contribute to that library instead of maintaining another one? Just a thought. thx.

**Comment by canhlinh** [comment]
@suntong I'm very busy now. I can not join the we him
