### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ghost** [canhlinh/gphoto#4]
Could you please add a little bit more documentation on how to install and use your project? 
Thanks :)

**Comment by canhlinh** [comment]
@vovler I'm not sure people will using this lib. It's a non-official upload tool to upload file to google photo.

@vovler If you have a base of golang. Please look around at the test file https://github.com/canhlinh/gphoto/blob/master/client_test.go

**Comment by ghost** [comment]
@canhlinh Many users choose to not use the API due to it's limitations. I found that your project uses the cookies which is perfect. 

I'm not much into golang, but It's not hard to understand the functionality of each function. Could you just help with the installation process?

Forwarding me to some URL that explains it, is more than enough :)

**Comment by canhlinh** [comment]
@vovler Ya. I'll add documentation.

**Comment by canhlinh** [comment]
@vovler FYI, I've made a PR for this request https://github.com/canhlinh/gphoto/pull/5

**Comment by ghost** [comment]
Didn't you mean
`go get -u github.com/canhlinh/gphoto`
Instead of 
`go get -u github.com/jinzhu/gorm `

Anyway, I was able to install it and noticed that moving the files to another album fails to get the tokenn, removed the move to another album thing, so now it works without it. 

Great project overall!

**Comment by canhlinh** [comment]
@vovler Sorry, I got a typo. Fixed.

**Comment by canhlinh** [comment]
@vovler Isn't that the documentation stratify you ?

**Comment by ghost** [comment]
It's great! :)

**Comment by canhlinh** [comment]
Just concern why did you unstar ?

**Comment by ghost** [comment]
I'm new here and didn't knew how to track the project. So I just pressed everything on the top. Later on I just removed it. Didn't knew it meant so much. There you go, Star'ed again :)
